name: Deploy application

on:
  push:
    branches:
      - main
    tags:        
      - '*' 


jobs:
  build-publish:
    name: Build, Publish
    runs-on: ubuntu-latest
      - uses: actions/checkout@v4
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
